apiVersion: v2
name: nsdf-intersect
description: "NSDF INTERSECT Diffraction Services"
version: 0.1.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: "^2.9.1"
