# global values used by this chart
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  kubeVersion: ""

### Generic Kubernetes parameters ###

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
extraDeploy: [] # dynamic Kubernetes templates

# TODO this probably has to be configured based on the system
podSecurityContext:
  enabled: false
  fsGroup: 1001
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: false

podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft

### Shared Volume Mount ###

volumeMount:
  dashboardPath: "/share"
  dashboardServicePath: "/share"

extraVolumes:
  - name: bragg-volume
    emptyDir: {}
  - name: transition-volume
    emptyDir: {}
  - name: andie-volume
    emptyDir: {}
  - name: scientist-cloud-volume
    persistentVolumeClaim:
      claimName: scientist-cloud-pvc

### Section that needs to be fixed ###
# TODO: fix this to make sense for this application
pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""
autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPUUtilizationPercentage: ""
  targetMemoryUtilizationPercentage: ""
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
updateStrategy:
  type: RollingUpdate
priorityClassName: ""
topologySpreadConstraints: []
schedulerName: ""
terminationGracePeriodSeconds: ""
lifecycleHooks: {}
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
# extraVolumes: []
extraVolumeMounts: []
initContainers: []
sidecars: []

### NSDF Diffraction Dashboard ###

dashboard:
  enabled: true

  ### container image
  image:
    registry: ghcr.io
    repository: nsdf-fabric/intersect-dashboard
    tag: "latest"
    digest: ""
    pullPolicy: ""
    pullSecrets: []

  diagnosticMode:
    enabled: false
    command:
      - sleep
    args:
      - infinity

  replicaCount: 1

  containerPorts:
    http: 10042

  extraContainerPorts: []

  extraVolumeMounts:
    - name: bragg-volume
      mountPath: /usr/src/dashboard/bragg_volume
    - name: transition-volume
      mountPath: /usr/src/dashboard/transition_volume
    - name: andie-volume
      mountPath: /usr/src/dashboard/andie_volume
    - name: scientist-cloud-volume
      mountPath: /usr/src/dashboard/scientist_cloud_volume

  # TODO figure out halfway decent probes

  livenessProbe: # the application developers should help determine sane default params
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  readinessProbe: # the application developers should help determine sane default params
    enabled: true
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  startupProbe: # the application developers should help determine sane default params
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}

  resources:
    limits: {}
    requests: {}

  command: []
  args: []
  hostAliases: []

  ### Traffic exposure

  service:
    type: ClusterIP
    port: 10042
    nodePort: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}

  ingress:
    enabled: false
    pathType: ImplementationSpecific
    hostname: intersect-nsdf-dashboard.local
    ingressClassName: ""
    path: /
    annotations: {}
    tls: false
    selfSigned: false
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
    extraRules: []

### NSDF-INTERSECT Diffraction Dashboard Service

dashboardService:
  enabled: true

  ### container image
  image:
    registry: ghcr.io
    repository: nsdf-fabric/intersect-service
    tag: "latest"
    digest: ""
    pullPolicy: ""
    pullSecrets: []

  diagnosticMode:
    enabled: false
    command:
      - sleep
    args:
      - infinity

  livenessProbe: # the application developers should help determine sane default params
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  readinessProbe: # the application developers should help determine sane default params
    enabled: true
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  startupProbe: # the application developers should help determine sane default params
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}

  resources:
    limits: {}
    requests: {}

  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  command: []
  args: []

  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""

  extraVolumeMounts:
    - name: bragg-volume
      mountPath: /usr/src/dashboard_service/bragg_volume
    - name: transition-volume
      mountPath: /usr/src/dashboard_service/transition_volume
    - name: andie-volume
      mountPath: /usr/src/dashboard_service/andie_volume
    - name: scientist-cloud-volume
      mountPath: /usr/src/dashboard_service/scientist_cloud_volume

### Kubernetes role stuff

serviceAccount:
  create: false
  annotations: {}
  name: ""
  automountServiceAccountToken: true

### application stuff
#
# See README on format
intersectConfig: {}
