# python slim image 
FROM python:3.10-slim

WORKDIR /usr/src/storage_service

RUN python -m pip install python-dotenv boto3==1.35.99

COPY ./services/storage_service.py ./storage_service.py
COPY ./services/constants.py ./constants.py

EXPOSE 10044

ENTRYPOINT ["python" ,"storage_service.py"]
