# python slim image 
FROM python:3.10-slim

WORKDIR /usr/src/dashboard_service

RUN python -m pip install intersect-sdk[amqp]
RUN python -m pip install pyyaml

COPY ./services/dashboard_service.py ./dashboard_service.py
COPY ./services/constants.py ./constants.py
COPY ./config/config_service.yaml /app/config_default.yaml
COPY ./config/config_dashboard.yaml /app/config_dashboard_default.yaml

EXPOSE 10043

ENTRYPOINT ["python", "dashboard_service.py"]
