# python slim image 
FROM python:3.10-slim

WORKDIR /usr/src/storage_service
COPY storage_service.py ./storage_service.py

RUN python -m pip install python-dotenv boto3==1.35.99

EXPOSE 10044

ENTRYPOINT ["python" ,"storage_service.py"]

