apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.dashboard.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.dashboard.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.dashboard.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.dashboard.service.type }}
  {{- if and .Values.dashboard.service.clusterIP (eq .Values.dashboard.service.type "ClusterIP") }}
  clusterIP: {{ .Values.dashboard.service.clusterIP }}
  {{- end }}
  {{- if .Values.dashboard.service.sessionAffinity }}
  sessionAffinity: {{ .Values.dashboard.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.dashboard.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.dashboard.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.dashboard.service.type "LoadBalancer") (eq .Values.dashboard.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.dashboard.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.dashboard.service.type "LoadBalancer") (not (empty .Values.dashboard.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.dashboard.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.dashboard.service.type "LoadBalancer") (not (empty .Values.dashboard.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.dashboard.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.dashboard.service.type "NodePort") (eq .Values.dashboard.service.type "LoadBalancer")) (not (empty .Values.dashboard.service.nodePort)) }}
      nodePort: {{ .Values.dashboard.service.nodePort }}
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}

