apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scientist-cloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: linode-block-storage-retain
