brokerPassword: "CHANGEME"
intersect:
  proxy-http-server:
    app:
      password:
        isSecret: false
        hardcoded: "CHANGEME"
  campaign-orchestrator:
    app:
      apiKey:
        # Must be at least 32 characters
        hardcoded: "CHANGEME_MIN_32_CHARS_REPLACE_ME_NOW"
