[project]
name = "nsdf-intersect-storage"
version = "0.1.0"
description = "The NSDF-INTERSECT storage service"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv",
    "boto3==1.35.99", 
    "pyyaml",
]
