######################
#### ANCHORS #########
######################
# anchors are just a useful feature so you don't repeat yourself in the config file


.anchors:
  # proxy
  proxy:
    systemName: &proxy-systemName "nsdf.cloud.diffraction."
    log_level: &proxy-loglevel "debug"  # set to "debug" if you want extremely verbose output, including of the messages themselves

    server:
      serverUsername: &proxy-serverUsername "proxy_username"
      serverContainerPort: &proxy-serverPort 9071 # you do not have to set this value, it will be 8080 if you don't. This is mostly to avoid conflicts with other applications.

  # message plane
  messageBroker:
    username: &messageBroker-username "controller"
    internalHost: &messageBroker-internalHost "nsdf-intersect-intersect-message-broker-1"
    # based off of templates/rabbitmq-secret.yaml, this is a hardcoded secret name we can reference across numerous applications
    brokerSecretName: &messageBroker-password "nsdf-intersect-broker-secret"
    brokerSecretKey: &messageBroker-passwordKey "rabbitmq-password"
    amqpNodePort: &messageBroker-amqpNodePort 30010
    mqttNodePort: &messageBroker-mqttNodePort 30011
    #stompNodePort: &messageBroker-stompNodePort 30012
    managerNodePort: &messageBroker-managerNodePort 30013
    metricsNodePort: &messageBroker-metricsNodePort 30014
    distNodePort: &messageBroker-distNodePort 30015
    epmdNodePort: &messageBroker-epmdNodePort 30016

commonLabels: {}
commonAnnotations: {}

# provide a real value in the secret file
brokerPassword: ""

intersect:
  proxy-http-server:
    enabled: true
    service:
      type: ClusterIP
      port: *proxy-serverPort
    # you do not have to set this value, it will be 8080 if you don't.
    containerPort: *proxy-serverPort
    app:
      username: *proxy-serverUsername
      topic_prefix: *proxy-systemName
      log_level: *proxy-loglevel
      broker:
        username: *messageBroker-username
        host: *messageBroker-internalHost
        password:
          isSecret: true
          secretName: *messageBroker-password
          secretKey: *messageBroker-passwordKey

  intersect-message-broker-1:
    image: 
      debug: true
    auth:
      username: *messageBroker-username
      existingPasswordSecret: *messageBroker-password
    # this example will use a NodePort service
    service:
      type: NodePort
      nodePorts:
        amqp: *messageBroker-amqpNodePort
        dist: *messageBroker-distNodePort
        manager: *messageBroker-managerNodePort
        epmd: *messageBroker-epmdNodePort
        metrics: *messageBroker-metricsNodePort
      extraPorts:
        - name: mqtt
          port: 1883
          targetPort: 1883
          nodePort: *messageBroker-mqttNodePort
        #- name: stomp
        #  port: 61613
        #  targetPort: 61613
        #  nodePort: *messageBroker-stompNodePort
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false  
    resources:
      requests:
        memory: "2Gi"
        # cpu: "8"
        # ephemeral-storage: "2Gi"
      limits:
        # NOTE: the default RabbitMQ chart REQUIRES you to set the "memory" value EVEN IF .Values.intersect-message-broker-1.memoryHighWatermark.type is "absolute"
        # this got fixed on a later version of the RabbitMQ chart than what we're using: https://github.com/bitnami/charts/commit/b92af12ad55e92c8b1377987b222090787d23b02
        memory: "4Gi"
        # cpu: "16"
        # ephemeral-storage: "4Gi"
    # need to override extraConfiguration because we need to set a management path prefix
    #extraConfiguration: |-
      #default_vhost = /
      #{{- if .Values.resources.limits.storage }}
      #disk_free_limit.absolute = {{ .Values.resources.limits.storage }}
      #{{- else }}
      #disk_free_limit.relative = 0.4
      #{{- end }}
      #{{- if .Values.resources.requests.cpu }}
      #delegate_count = {{ .Values.resources.requests.cpu }}
      #{{- end }}
      #mqtt.max_session_expiry_interval_seconds = infinity
      # set this to the maximum allowed by rabbitmq - https://www.rabbitmq.com/docs/configure#config-items
      #max_message_size = 536870912
      #management.path_prefix = /messages

  intersect-storage-1:
    # we shouldn't need MINIO for this deployment
    enabled: false
